name: my first workflow
on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo 
          uses: actions/checkout@v4
        - name: list and read file
          run: | 
            echo "my first git actions job"
            ls -latr
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "run for cover, I am a Dragon...RAW RAW" >> dragon.txt
      
