name: Generate ASCII Artwork
on:
  push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v4

    - name: Executing Shell Script 
      run: |
        cd .github/workflows
        chmod +x ascii-script.sh
        ./ascii-script.sh 

  test_job2:
    needs: ascii_job
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10sec
        run: sleep 10
